// Generates app/engine/hand-ranking.ts: the 169 starting-hand classes ordered by all-in equity
// against one random hand (seeded Monte Carlo, so the output is reproducible).
//   npx tsx scripts/gen-hand-ranking.ts
import { writeFileSync } from "node:fs";

import { DECK, evaluate, seededRandom } from "../app/engine/cards.ts";
import { ALL_CLASSES, combosOf } from "../app/engine/hand-classes.ts";

const ITERATIONS = 40000;
const rand = seededRandom(20260929);

function equityVsRandom(cls: string): number {
    const combos = combosOf(cls);
    let score = 0;
    for (let i = 0; i < ITERATIONS; i++) {
        const hero = combos[i % combos.length];
        const deck = DECK.filter((c) => c !== hero[0] && c !== hero[1]);
        // partial Fisher-Yates: 2 villain cards + 5 board cards
        for (let k = 0; k < 7; k++) {
            const j = k + Math.floor(rand() * (deck.length - k));
            [deck[k], deck[j]] = [deck[j], deck[k]];
        }
        const board = deck.slice(2, 7);
        const h = evaluate([hero[0], hero[1], ...board]);
        const v = evaluate([deck[0], deck[1], ...board]);
        score += h < v ? 1 : h === v ? 0.5 : 0;
    }
    return score / ITERATIONS;
}

const ranked = ALL_CLASSES.map((cls) => ({ cls, eq: equityVsRandom(cls) })).sort((a, b) => b.eq - a.eq);
const body = ranked.map((r) => `    ["${r.cls}", ${r.eq.toFixed(4)}]`).join(",\n");
writeFileSync("app/engine/hand-ranking.ts", `// GENERATED by scripts/gen-hand-ranking.ts. Do not edit by hand.
// The 169 starting-hand classes ordered by all-in equity against one random hand
// (${ITERATIONS} seeded simulations each). This is a standard approximation of preflop strength;
// it slightly undervalues suited connectors compared to how they play in multiway pots.
export const HAND_RANKING: [string, number][] = [
${body}
];
`);
console.log("top 10:", ranked.slice(0, 10).map((r) => `${r.cls} ${(r.eq * 100).toFixed(1)}%`).join(", "));
console.log("bottom 3:", ranked.slice(-3).map((r) => `${r.cls} ${(r.eq * 100).toFixed(1)}%`).join(", "));
